version: "3.9"
services:
  api:
    image: node:20-alpine
    working_dir: /usr/src/app
    entrypoint: ["/bin/sh","-lc","chmod +x docker/dev-entrypoint.sh && docker/dev-entrypoint.sh"]
    env_file: [ ./Backend/api/.env ]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      NODE_ENV: development
    volumes:
      - ./Backend/api:/usr/src/app
      - /usr/src/app/node_modules
    ports: ["3000:3000"]
