name: Flutter CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.x' # usa sempre a versão estável do Flutter

      - name: Install dependencies
        run: flutter pub get
        working-directory: Frontend

      - name: Analyze (lint)
        run: flutter analyze
        working-directory: Frontend

      - name: Run tests
        run: flutter test --no-pub
        working-directory: Frontend